# Generated by Django 5.2.4 on 2025-08-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descripcion_caso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('asesoria_legal_integral', 'Asesoría Legal Integral'), ('contratacion_publica', 'Contratación Pública y Asesoría a Empresas'), ('defensa_penal', 'Defensa Penal Estratégica'), ('litigio_civil_mercantil', 'Litigio Civil y Mercantil'), ('derecho_laboral', 'Derecho Laboral y Seguridad Social'), ('derecho_familia', 'Derecho de Familia y Niñez'), ('constitucion_empresas', 'Constitución y Regularización de Empresas'), ('recuperacion_cartera', 'Recuperación de Cartera Vencida'), ('defensa_administrativa', 'Defensa Administrativa y Sancionatoria'), ('derecho_militar', 'Derecho Militar'), ('derecho_notarial', 'Derecho Notarial'), ('derecho_internacional', 'Derecho Internacional Privado')], default='asesoria_legal_integral', max_length=50),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
