# Generated by Django 5.2.4 on 2025-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita_descripcion_caso_cita_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.CharField(choices=[('virtual', 'Atención Virtual'), ('presencial', 'Atención Presencial')], default='virtual', max_length=20),
        ),
    ]
