# Generated by Django 5.2.4 on 2025-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cita_modalidad'),
    ]

    operations = [
    ]
