# Generated by Django 5.2.4 on 2025-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20250823_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='anios_experiencia',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes, 09h00-17h00', max_length=200),
        ),
        migrations.AddField(
            model_name='abogado',
            name='idiomas',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('de', 'Alemán'), ('pt', 'Portugués'), ('fr', 'Francés'), ('ot', 'Otros')], default='es', max_length=20),
        ),
        migrations.AddField(
            model_name='abogado',
            name='licenciatura_titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título de Licenciatura'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='licenciatura_universidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Licenciatura - Universidad'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='maestria_titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título de Maestría'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='maestria_universidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Maestría - Universidad'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de Registro Profesional'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
