# Generated by Django 5.2.4 on 2025-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_abogado_anios_experiencia_abogado_horario_atencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='abogado',
            name='idiomas',
        ),
        migrations.AddField(
            model_name='abogado',
            name='idiomas',
            field=models.ManyToManyField(blank=True, to='agenda.idioma'),
        ),
    ]
