# Generated by Django 5.2.4 on 2025-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_idioma_remove_abogado_idiomas_abogado_idiomas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='abogado',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abogado',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
